#pragma once
#define UFO_ICON_FONT_ACTOR u8"\ue000"
#define UFO_ICON_FONT_SPRITE u8"\ue001"
#define UFO_ICON_FONT_ANIMATION u8"\ue000"
#define UFO_ICON_FONT_BACKGROUND_SPRITE u8"\ue000"
#define UFO_ICON_FONT_PLATFORMER_COLLISION_RECTANGLE u8"\ue000"
#define UFO_ICON_FONT_TILE_MAP u8"\ue005"

#define UFO_ICON_FONT_PLAY_BUTTON u8"\ue000"
#define UFO_ICON_FONT_PAUSE_BUTTON u8"\ue000"
