#pragma once
#define UFO_ICON_FONT_ACTOR u8"\ue000"
#define UFO_ICON_FONT_SPRITE u8"\ue001"
#define UFO_ICON_FONT_ANIMATION u8"\ue000"
#define UFO_ICON_FONT_BACKGROUND_SPRITE u8"\ue000"
#define UFO_ICON_FONT_PLATFORMER_COLLISION_RECTANGLE u8"\ue000"
#define UFO_ICON_FONT_TILE_MAP u8"\ue005"

#define UFO_ICON_FONT_PLAY_BUTTON u8"\ue100"
#define UFO_ICON_FONT_PAUSE_BUTTON u8"\ue101"
#define UFO_ICON_FONT_VISIBLE u8"\ue102"
#define UFO_ICON_FONT_INVISIBLE u8"\ue103"
//#define UFO_ICON_FONT_FILE u8"\ue104"
//#define UFO_ICON_FONT_FOLDER u8"\ue105"
