#pragma once
#include "../object.h"
#include "../dynamic_array.h"
#include "console.h"
#include <vector>
#include "../../src/ufo_macros.h"

namespace beam_test2{

class Actor : public ufo::gc::Object{
public:
    Actor(){}
};

class ReferenceHolder : public ufo::gc::Object{
public:
    ufo::gc::Object* ref = nullptr;
};

class Main : public ufo::gc::Root{
public:

    ufo::gc::DynamicArray<Actor*> objects;

    ufo::gc::Object* o = nullptr;
    ReferenceHolder* r = gc.New<ReferenceHolder>();
    ReferenceHolder* s = gc.New<ReferenceHolder>();

    Main(){
        r->ref = s;
        s->ref = r;

        for(int i = 0; i < 20; i++) objects.push_back(gc.New<Actor>());

    }

    //This part could be an autogenerated macro or something.
    void OnMark() override {
        objects.Mark();
        mark(o);
        mark(s);
        mark(r);
    }

    void Update(){
        ufo::gc::Object* shortlived = gc.New<ufo::gc::Object>();

        for(const Actor* obj : objects){
            Console::PrintLine("obj",obj->name);
        }

        for(ufo::gc::DynamicArray<Actor*>::iterator it = objects.begin(); it != objects.end(); it++){
            Console::PrintLine("obj",(*it)->name);
        }
    }

    void Start(){
        std::string inp = "";

        while(inp != "q"){
            Update();
            gc.Collect();

            inp = Console::In("Command:");
        }
    }

};
}
